### ISSUE TITLE
>mfw no composer

### ISSUE THREAD

**Issue by olso** [josephernest/void#2]

**Comment by josephernest** [comment]
I didn't know what Composer is (even if I saw this name everywhere all the time) until today when I looked what it is about. Now I understand it's great and I will surely use it for larger projects.

But the philosophy for this project is: the least number of lines of code, the least number of layers, of required tools.

Installing Apache + PHP is already enough for someone who is not familar yet with all web technologies. That's why I would avoid to require having to install another tool, Composer. 
But for bigger projects, ok, I'll use it!

**Comment by olso** [comment]
Ok then :+1: closing

**Comment by josephernest** [comment]
PS: think about people who use shared hosting (like me until very recently), and who cannot install composer

**Comment by olso** [comment]
@josephernest 

1. IMO, composer should only be used locally anyway. People shouldn't use composer on production environment. Make your changes locally, then push them to server (along with vendor folder)

2. What do you mean. Composer works on Windows too, last time I checked.

**Comment by josephernest** [comment]
Oh ok @olso, then i'll learn this new tool for next project!

**Comment by olso** [comment]
@josephernest 

Look here https://github.com/laravel/laravel/blob/master/.gitignore

**/vendor** folder is ignored, if not, it will only make your commits unreadable/less obvious if anything changes/updates

It has benefits, when you define your requirements in https://github.com/laravel/laravel/blob/master/composer.json

you only have to composer install/update, select what version you want, bla bla

All packages are here https://packagist.org/
