### ISSUE TITLE
100 lines troll :)

### ISSUE THREAD

**Issue by nderambure** [josephernest/void#24]
Hey !

I really agree with the principle of void, but I would like to relaunch the 100 lines troll problem :)
For an unique reason actually : code lisibility.
If the index.php file is formatted with some PHP standards (anyone), we all be able to fork and modify easily. For now, it's really a pain :)
I know that it would take then more than 100 lines but I'm sure that with some optimisations, it will be closed :)

Additionnaly, some standard formatted comments would be great too (and not count in the 100 lines obviously).

Just saying :)

**Comment by nderambure** [comment]
I add that Parsedown class is more than 100 lines hihihihi

**Comment by josephernest** [comment]
Haha :) Good idea to restart this troll! But unfortunately this is really part of the initial philosophy : 100 lines max :)

PS : yes Parsedown.php is more than 100 lines, but... you can *remove* the Parsedown parser if you like, and Void will still work (but you will have to write the articles in plain HTML instead of Parsedown, but it will still work) ;)
