### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by marcinlawnik** [josephernest/void#4]
Would you consider using composer for the parsedown library or do you just want it to be download-and-drive?

**Comment by josephernest** [comment]
I prefer to be download-and-drive. The intent here is minimalism, having to ask the final user to install another tool is not something that I'd wish.

It's easier for the final user to have the file there, ready-to-use, rather than having to install a tool named Composer (that lots of people, like me until yesterday, don't know).

We discussed this here: https://github.com/josephernest/void/issues/2

**Comment by marcinlawnik** [comment]
I didn't see it ;) I have a proposal, you could use composer so that your library is up to date, and still publish ready releases with github release system that are just unzip-and-use ;) What about that?

**Comment by josephernest** [comment]
Good idea! I will probably use this. I'll close the issue for now.
